version: 20
jobs:
- name: test
  jobExecutor: test-exec
  steps:
  - !BuildImageStep
    name: Build Image
    tags: dip:dev
    publish: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: run container
    image: dip:dev
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
