version: 20
jobs:
- name: Pull project
  jobExecutor: Prod
  steps:
  - !CheckoutStep
    name: dip
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: check pwd and ls
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - pwd
      - ls
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
